version: '2'
services:
  nginx:
    build: ./nginx
    ports:
     - "8080:80"
    volumes:
     - ~/PhpstormProjects:/usr/share/nginx/html
    links:
     - node
     - php73
     - php74
     - php80

  node:
    build: ./node
    ports:
    - "9014:8888"
    volumes:
    - ~/PhpstormProjects:/var/www/html
    links:
    - mysql57

  php73:
    build: ./php73
    ports:
     - "9073:9000"
    volumes:
     - ~/PhpstormProjects:/var/www/html
    links:
     - mysql57

  php74:
    build: ./php74
    ports:
      - "9074:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mysql57

  php80:
    build: ./php80
    ports:
      - "9080:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mysql57

  mysql57:
    build: ./mysql57
    environment:
     - MYSQL_ROOT_PASSWORD=mysql57secret
    ports:
     - "9017:3306"
    volumes:
     - ~/PhpstormProjects/docker-dev-phpstorm/data/mysql57:/var/lib/mysql
