version: '2'
services:
  nginx:
    build: ./nginx
    ports:
     - "8080:80"
    volumes:
     - ~/PhpstormProjects:/usr/share/nginx/html
    links:
     - node8
     - php56
     - php70
     - php71
     - php72

  node6:
    build: ./node8
    ports:
    - "9008:8888"
    volumes:
    - ~/PhpstormProjects:/var/www/html
    links:
    - mysql57

  php56:
    build: ./php56
    ports:
     - "9056:9000"
    volumes:
     - ~/PhpstormProjects:/var/www/html
    links:
     - mysql57

  php70:
    build: ./php70
    ports:
     - "9070:9000"
    volumes:
     - ~/PhpstormProjects:/var/www/html
    links:
     - mysql57

  php71:
    build: ./php71
    ports:
     - "9071:9000"
    volumes:
     - ~/PhpstormProjects:/var/www/html
    links:
     - mysql57

  php72:
    build: ./php72
    ports:
     - "9072:9000"
    volumes:
     - ~/PhpstormProjects:/var/www/html
    links:
     - mysql57

  mysql57:
    build: ./mysql57
    environment:
     - MYSQL_ROOT_PASSWORD=mysql57secret
    ports:
     - "9017:3306"
    volumes:
     - ~/PhpstormProjects/.docker/data/mysql57:/var/lib/mysql
