version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ~/GitHub:/usr/share/nginx/html
    links:
      - node
      - php74
      - php80
      - php81

  node:
    build: ./node
    ports:
      - "9014:8888"
    volumes:
      - ~/GitHub:/var/www/html

  php74:
    build: ./php74
    ports:
      - "9074:9000"
    volumes:
      - ~/GitHub:/var/www/html

  php80:
    build: ./php80
    ports:
      - "9080:9000"
    volumes:
      - ~/GitHub:/var/www/html

  php81:
    build: ./php81
    ports:
      - "9081:9000"
    volumes:
      - ~/GitHub:/var/www/html
